### ISSUE TITLE
Shipping Slowdowns

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#104]
There are real concerns from the Lightspeed team that the shipping process is slowing down their ability to get masks out the door. Can someone please work with them to fully understand the challenges?

One thing that I am aware is causing challenges is that there are cases when the requestor knows their address more-so than Google might. I'm questioning whether the use of this API is helping or hindering the shipping process?

**Comment by markfreedmantulip** [comment]
most of the issues we are seeing are due to the mass import of MOA's.  Steve is fixing this  now.

Moving forward we will probably make a change to when the address components are verified but genrally speaking this is not a problem up until the first MOA upload
