### ISSUE TITLE
Login - “Phone number” >>>> “Login ID (10 digit number: eg. 2334447778):”

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#115]

**Comment by ianslai** [comment]
Apps to share / PPE Logistics / Sign into account
Possibly also:
Apps to share / PPE Logistics / Create new account

**Comment by ilya-bass** [comment]
These must be unique in the PPEL universe, so it can't be arbitrary numbers, otherwise there will be collisions.

**Comment by jackkrooss** [comment]
yes, it should say number taken or something

**Comment by ilya-bass** [comment]
My point is that if we don't suggest it's a phone number, then collisions are more likely.  Sounds like you still want to call this a 10-digit number and not a phone number?

**Comment by jackkrooss** [comment]
I guess it is OK to call it a phone number. It is just confusing because it
has nothing to do with being contacted. People are familiar with using
email for IDs in this manner, but not so much phone numbers. Why does this
have to be a number? Could it be an alphanumeric ID?

**Comment by ilya-bass** [comment]
So the other issue is all existing customers -- we have to be careful not to confuse them.  I think for at least some initial transition time we have to note that the ID is what used to be called a phone number.

**Comment by jackkrooss** [comment]
Agreed

**Comment by jackkrooss** [comment]
We can go ahead and do this.

Change label on "Let's set up your account to "User ID (email, phone number or other unique ID)"

Change label on screen when you already have an account to"User ID (email, phone number or other unique ID)" and get rid of text above "Please type in..."

Need to look at parsing code to not restrict to just phone numbers.
