### ISSUE TITLE
Please fill out following information - several changes see comment

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#116]
“Healthcare Institution” >>>> “Organization”
“Healthcare Institution Name” >>>> 
“Organization Name (max 30 characters: eg. Massachusetts General Hospital):” 
“Healthcare Institution Name” >>>> 
“Organization Address (add1, add2, city, state, zip: eg. 55 Fruit St, Suite 100, Boston, MA 02114):”
“Delivery Address (if different): >>>>
“Delivery Address (add1, add2, city, state, zip: eg. 58 Fruit St,  Dock 12, Boston, MA 02114):”
“Delivery Notes (ie: Suite123 or meet in the parking lot):” >>>>
“Delivery Notes (eg. Courier call me at 555-234-6789 when you are close):”
“Primary Contact Info (Your Information)” >>>> “Your Contact Information”
“Your full name:” >>>> “Full Name (first last, eg. Janet Smith):”
“Your phone number (US only):” >>>> “Phone Number (US only, eg. 555-123-9876):”
“Your email:” >>>> “Email (eg. sombody@someplace.com):”
“Your Affiliation with Institution:” >>>> “Your Affiliation With Organization:”

**Comment by ianslai** [comment]
Apps to Share / Customer Order / Login Workflows / New Visitor Form
Possibly also:
Apps to Share / Customer Order / Login Workflows / Add user to account
