### ISSUE TITLE
Create / Edit Product - It’s impossible to enter decimal amounts in the Value (USD) slot (duplicate)

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#119]

**Comment by nimsarr** [comment]
Duplicate of https://github.com/tulip/ppe-logistics/issues/162

**Comment by jackkrooss** [comment]
yup, thanks

**Comment by jackkrooss** [comment]
NO ACTUALLY, different.

**Comment by jackkrooss** [comment]
Decimal $$ is self explanatory, but decimal product means that you can have
a fraction of a product used for a child product. Example is that you have
a spool of elastic that you use for headbands. The spool is 200 feet long.
You use 2 feet of elastic per headband. So you use .01 elastic spools per
headband.

**Comment by jackkrooss** [comment]
Never mind, Simon was correct this is a duplicated. Fractional BOM stuff is
addressed in #163
