### ISSUE TITLE
Operator Functions (under Operator button) - Contact name is the same for all even though I put in different contact names for each site.

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#120]

**Comment by ianslai** [comment]
@jackkrooss after digging into the code a bit, I think what's going on is that it's not showing the Contact's name, it's showing your own username.  So it wouldn't actually vary across sites.

In the example below, I've put in different contacts for each of the test supply sites (Grape Garden, Vegetable Valley) in my test org, but neither of them are 'Ian "Supplier Manager" Lai', which is the name I put in for my own account:

![Operator Functions](https://user-images.githubusercontent.com/7863470/82390690-651eef80-9a0d-11ea-914e-caf347c85f1f.png)

**Comment by jackkrooss** [comment]
That makes sense.

**Comment by jackkrooss** [comment]
Sorry for the confusion.

**Comment by jackkrooss** [comment]
It does seem strange that this is the one place that the user name is
displayed. I think we should try to make the displays more consistent
across the app. I will look into this further. Thank you for sussing it out.

**Comment by ianslai** [comment]
No worries.  How do you want to handle this ticket @jackkrooss ?  I'm not sure if we should close it, or if you want to assign the ticket to yourself to investigate a more consistent display?

**Comment by jackkrooss** [comment]
Close it.
