### ISSUE TITLE
Add Image - Increase size of preview window. Remove Menu button. 

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#144]

**Comment by ianslai** [comment]
This tickets affects both of these steps:

Supplier Manager / Product Creator / Add Image
Apps to Share / Production Worker / Add Image

**Comment by ianslai** [comment]
This is apparently not currently possible in Tulip.

The image upload is done via a built-in Photo Input widget.  The only way you can change sizing within that widget is by altering the font size of the prompt text, and that doesn't seem to affect the actual size of the preview:

![photo input](https://user-images.githubusercontent.com/7863470/82739912-d3b3c400-9d11-11ea-93e6-32ab1f3035da.png)

![image preview](https://user-images.githubusercontent.com/7863470/82739929-fcd45480-9d11-11ea-8ffb-ff9492820189.png)

**Comment by jackkrooss** [comment]
can not be done... close
