### ISSUE TITLE
Welcome to the PPE Logistics Request Form! - Update. Get rid of No button. Improve appearance

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#149]

**Comment by ilya-bass** [comment]
@jackkrooss thoughts on improving the appearance?  Might need a collaboration session to discuss UI tweaks?

**Comment by jackkrooss** [comment]
Yes. Agreed. I spent some time demoting things that fall into this
category. Goal is to nail low hanging fruit things up and consider the
scope of effort of a more general UI overhaul.
