### ISSUE TITLE
Workspace Navigation - Should have supplier name on screen

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#150]

**Comment by ianslai** [comment]
Supplier Manager / Navigation - Supplier Manager / App menu
Supplier Manager / Navigation - Courier Manager / App menu

Possibly also:
Supplier Manager / Navigation - CSR / App menu
Supplier Manager / Navigation - SupplierSite / App menu
Supplier Manager / Navigation - Tulip / App menu

**Comment by ryuncom** [comment]
@ianslai I think in Supplier Manager / Navigation - Tulip --> there is already "Choose a supplier" section in the upper portion of the screen. I think that should suffice for putting the supplier name in the screen. How do you think?

**Comment by jackkrooss** [comment]
@ryuncom what is meant here is that the name of the workspace is not listed at the top. For instance, 

PPE2PHL
Workspace Navigation

The Choose Supply Site, refers to the the supply sites, not the workspace. A (Supplier) workspace has multiple supply sites. Those are listed in the drop down, but nowhere is the workspace supplier listed.

**Comment by ryuncom** [comment]
@jackkrooss 
Do you mean at "Supplier Manager / Navigation - Supplier Manager / App menu"?
If you mean we need to put the supplier name there, then it's already taken care of.
What I am asking is the case of "Supplier Manager / Navigation - Tulip / App Menu".
In here, we can choose both supplier and supplier site, so maybe, we do not need to put the name of the supplier.

Also, how about the case of "Supplier Manager / Navigation - SupplierSite / App menu"?
Do we want to put the supplier site name there, or the supplier name?

**Comment by ianslai** [comment]
@ryuncom Looking at this again, I don't know how one gets to "Supplier Manager / Navigation - Tulip / App Menu", but it looks like maybe it's a debugging screen for in-house use?  Since customers aren't supposed to be able to choose which supplier they represent.  That said, since there's already a drop-down in that screen, I agree it wouldn't make sense to add there.

**Comment by jackkrooss** [comment]
Correct it should not be possible to get to it. There is, or was, another
BUG ticket that identified a way to get there during the signup process if
you chose a Menu button, but that might have been fixed.

**Comment by ianslai** [comment]
Changes made thus far have been published in Version 29.
