### ISSUE TITLE
MiamiMedCOVIDHelp Dashboard showing workcenter IDs instead of names

### ISSUE THREAD

**Issue by ianslai** [tulip/ppe-logistics#183]
Per Megan Matthew:

> For some reason, one of our institutions is coming up like this in the Dashboard, it looks fine on the Tulip end of things though. It's called "holy cross Hospital"

![image (1)](https://user-images.githubusercontent.com/7863470/82500848-3b73d000-9ac2-11ea-9bdc-589bdc80f16e.png)

This is in the Executive Summary: https://www.ppelogistics.org/supplier/mmch/dashboard/01

**Comment by ianslai** [comment]
This is indeed due to the workcenter ID/name refactor.

To fix this, edit the [GS dashboard - PROD](https://datastudio.google.com/u/0/datasources/cc03478c-0e7e-4bea-9f34-20a734f79e99) data source and change the SQL to return the `wcname`.

Specifically, change line 2 from
```
	demandcenter AS customer,
```
to
```
	workcenters.wcname AS customer,
```

**Comment by ilya-bass** [comment]
Fixed. I checked other pages of the report, they seem fine.  There are a couple of data sources that still return the old column but they are not used in the active parts of the report.
