### ISSUE TITLE
Customers - After adding a customer but not entering an order, the customer does not show up in the customer manager.

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#186]

**Comment by jackkrooss** [comment]
Go to Create/Edit select an institution and create a new customer for the institution. Then go to Customers. New customer does not show up in list. Find it by selecting the institution and using the drop down. Note new customer is in REVIEW. Approve new customer. Still does not show up in list.

**Comment by jackkrooss** [comment]
I decided to try and add a bunch of customers to try to replicate the PPE2PHL Angela Court wcid issue, and I ran into this again. When you create a customer it does not show up in the customer list, howver when you add the first order it does and status is REVIEW.
![image](https://user-images.githubusercontent.com/64096573/87330068-dc906d00-c4ec-11ea-9cc2-d6a1b74968f9.png)

**Comment by jackkrooss** [comment]
When demoing PPEL to Resource 19 today, we experienced this issue. We created a new customer and then went to check the Customer Manager before entering the order. Now the customer is lost forever....

**Comment by ilya-bass** [comment]
@jackkrooss I spent about a couple of hours trying to hack it.  So far no luck.  Will try more tomorrow.

**Comment by ilya-bass** [comment]
ok, I tweaked the wording in the static text and in the post-save message.  Adding an item to a cart is enough to ensure the customer does not disappear.

Real fix requires too much hacking and I am giving up on that
