### ISSUE TITLE
PPE2PHL Angela Court wcid

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#206]
PPE2PHL Customer Manager still has the hieroglyph institutions: (edited) 

![image](https://user-images.githubusercontent.com/64096573/87326591-caf89680-c4e7-11ea-8204-2891153a8e22.png)

Use above info if you need to get into PPE2PHL:
PPE2PHL Support:
	PPE2PHL
	Login ID: 		9510000102
	PW:			7822450092 
	Name: 			PPEL Support
	Supplier:		PPE2PHL
	Supplier Manager PW: 	sourcePPE

Detective work.... Looking at PPE2PHL here is a screen from Create/Edit Customers which I got by using the dropdown to select Angela Court, and then the other dropdown to select Karin Purcell.

![image](https://user-images.githubusercontent.com/64096573/87326726-fb403500-c4e7-11ea-9ce9-ffeeb0f2fa01.png)

If I then click on Customers here is the screen which lists Angela Court/Karin Purcell:

![image](https://user-images.githubusercontent.com/64096573/87326806-18750380-c4e8-11ea-9d4a-78763cda454e.png)

Now page forward and we have Karen Purcell and hieroglyph:

![image](https://user-images.githubusercontent.com/64096573/87326921-39d5ef80-c4e8-11ea-811d-1f54a8489f30.png)

And page back and no Angela Court:

![image](https://user-images.githubusercontent.com/64096573/87327012-5f62f900-c4e8-11ea-871f-40cb058870df.png)

...and no longer in alphabetical order. I think the paging is messed up somehow, but not destructive.

When I leave the Customer manager screen and go back in I get Angela back:

![image](https://user-images.githubusercontent.com/64096573/87327154-8faa9780-c4e8-11ea-8784-e0e00a289ea9.png)

Note also that all messed up ones are status REVIEW

**Comment by ilya-bass** [comment]
I took the query directly from the connector function and ran it myself, and not seeing the same order of records, nor am I seeing Angela Court.  This is puzzling, as I am not sure how this gets transformed later on.  Either the query is not run with the same inputs or I am missing some logic elsewhere in the step.  I will continue debugging tonight.

**Comment by jackkrooss** [comment]
Correction, all the messed up ones are not status REVIEW. Seems unrelated to status

**Comment by jackkrooss** [comment]
Replicated issue with Kirby PPE Dreamworld in our dev env. Added a bunch of customers and they all listed fine on the first screen of the Customer Manager. Pressing the ">" to go to the second screen did nothing. But when I got the first screen full -- even before it ran over to screen 2 -- and pressed ">" I got a blank screen 2. Then going back by pressing "<" I got this:
![image](https://user-images.githubusercontent.com/64096573/87332334-3fcfce80-c4f0-11ea-9a67-b236a36a6ae0.png)

**Comment by jackkrooss** [comment]
Pressed Edit/Creat and then back to Customers and we are back to real Institution names:
![image](https://user-images.githubusercontent.com/64096573/87332527-87565a80-c4f0-11ea-9f75-f4ded8b97fc3.png)

**Comment by jackkrooss** [comment]
This is repeatable. Reenter the screen, all is OK, use ">" and then "<" it is messed up. I am not going to add any more customers just leave this for Ilya to look at.

**Comment by jackkrooss** [comment]
Kirby:
Phone: 2643383279
Password "supplier"

**Comment by ianslai** [comment]
When the page is initially loaded, it's using the **CSR - Customers 5 w/ org (wcid)** connector, which uses the `wcname`
from `workcenters` that is associated with the customer's orders (in the `demands` table) to display the institution.

But when you use the > and < nagivation buttons, it uses the **CSR - Customers 5 w/ org** connector, which uses the raw value of the `hospital` column for the customer to display the institution.

I imagine that we should just fix the navigation buttons to use the same connector, though I don't know why we're getting institution information from orders.

**Comment by jackkrooss** [comment]
I am having some computer issues. Should be back online soon.
