### ISSUE TITLE
Customer Manager / Editor retooling

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#211]
This issue addresses a scheme that Ian and I worked out this morning to improve the customer manager and the customer editor. One of the benefits is that it eliminates the dropdowns from the editor. The other benefit is that it eliminates duplicates of information and simplifies the Institution/Customer schema.

The basic idea is to eliminate editing of customer information on the Customer Manger screen, and instead permit the user to hit an Edit button which takes them to the new Customers and Orders Editor screen:
![image](https://user-images.githubusercontent.com/64096573/87595916-23749300-c6a4-11ea-873b-ab1bc664cf8a.png)

![image](https://user-images.githubusercontent.com/64096573/87596066-5880e580-c6a4-11ea-821d-aaf588c388a0.png)

**Comment by jackkrooss** [comment]
Note that the edit button atm is just a jump to the new screen, and does not populate the form on Customers and Orders Editor. I have simulated this on the bottom right for dev purposes with the dropdowns, but the idea is to lose the dropdowns and autopopulate the customer. 

The other functionality supported by this editor screen is entering new orders. This can be done by simply filling out an empty form. I believe this all just works now. You can also clear the form and fill out the form to create a new customer.

**Comment by jackkrooss** [comment]
Note that this new approach collapse a lot of the Institution/Customer stuff with multiple customers per Institution and Primary customers etc. I think this is a can of worms, and if we can get away with it it is better to just disable this functionality. I understand that under the hood it is still the same, but the multiple customers per institution will no longer be exposed to the user.

**Comment by ilya-bass** [comment]
ok, I made some progress, but there are a lot of fiddly bits still, and Save is not fully saving all the fields properly 
more tomorrow night

**Comment by jackkrooss** [comment]
tested and can not find any problems. I think it is good to go!

**Comment by ilya-bass** [comment]
thanks @jackkrooss 
I cleaned up the old hospital and customer dropdowns and their population -- that was the source of the slowdowns for MasksOn.  Found a bug where institution notes were not being saved, and fixed it.  
I agree, we should publish today; if you could give MasksOn a heads-up, and also confirm that slow load is fixed when published, that'd be great.  Let's take note of the previous app version before publishing, and be ready to rollback if something break in a major way.
