### ISSUE TITLE
Add customer name to shipping screen

### ISSUE THREAD

**Issue by jackkrooss** [tulip/ppe-logistics#215]
For some reason the shipping info does not include tha customer name and it is not available as a variable to add. Can this be added?

**Comment by ilya-bass** [comment]
@jackkrooss you mean Shipment Manager screen, right?  Just want to make sure.

**Comment by ilya-bass** [comment]
@jackkrooss I added the customer's name to the "destination" field.  A separate field is too much pain because this would mean new output of the connector function, necessitating changes in all the invisible rows.  I hope this is good enough?  It's not published but is in final review.  Can undo easily if needed.

**Comment by jackkrooss** [comment]
Thank you. Looking now.

**Comment by jackkrooss** [comment]
I think that is perfect! Great idea. Excellent. Thank you. We can close this.

**Comment by jackkrooss** [comment]
Actually, I am going to increase the size of the field, so we should not publish yet.

**Comment by jackkrooss** [comment]
Notes below are trying to debug Customer Name Fail Intermittant. Notes from Slack this am:
Jack Krooss  8:56 AM
@ilya, very strange. I was testing your new fix to the Shipment Manager and it looked great. Then I left the window to post my comment in github. When I went back the fix was gone:
8:56
image.png 
image.png







8:57
image.png 
image.png



Ilya Bass  8:57 AM
I'm away from the keyboard for a while

Jack Krooss  8:58 AM
I RETURN and SHIP and the fix is back:
8:58
image.png 
image.png


8:59
No problem, when you get a chance... Super strange. It is repeatable.
9:00
Once you leave the Tulip Player window and come back the fix is no longer active.

Ilya Bass  9:01 AM
When you say leave, what exactly do you do?
9:01
This is the desktop player?

Jack Krooss  9:01 AM
image.png 
image.png


9:01
Just go to any other window and then return to Tulip
9:01
Click on any other window
9:02
This may just be a Tulip bug and publishing would be fine, but it is strange

Ilya Bass  9:02 AM
Mind recording a screen video?

Jack Krooss  9:02 AM
Hmmm. never done that before, but I should learn. Do you have a favorite video app?

Ilya Bass  9:03 AM
I suppose you can use your phone :-)

Jack Krooss  9:03 AM
Yes, I could do that

Ilya Bass  9:03 AM
And make it a literal video :-)

Jack Krooss  9:03 AM
Will do

Ilya Bass  9:03 AM
I think SnagIt is free
9:04
So that's another option

Jack Krooss  9:05 AM
On it...
9:06
Not as simple as I thought to recreate. Working on it.

Jack Krooss  9:12 AM
It seems very intermittant. Sometimes I need to switch around a few times, but it eventually does get into the state whith no name in address:
image.png 
image.png


9:13
Will try to capture...

Ilya Bass  9:13 AM
It's incredibly strange. So you do nothing in Tulip itself in the meantime?

Jack Krooss  9:14 AM
Once in that state it stays there...
9:14
image.png 
image.png


9:15
Correct, nothing... very strange indeed
9:15
This may be a caching thing or something about the player ???
9:16
Maybe not a production issue, but very weird indeed

Ilya Bass  9:17 AM
You could try publishing and then seeing if it happens in production

Jack Krooss  9:17 AM
I think that is what I will do. No sense chasing ghosts
9:19
OK, pretty reliably if you leave the Tulip player and do something else for a few minutes and then go back it gets into the broken state

Ilya Bass  9:20 AM
I can play with it at home but not before 8 or so my time

Jack Krooss  9:20 AM
Intersting, when I try to Return when it is the broken state I get an error Error Processing Trigger Timer

Ilya Bass  9:21 AM
That worries me :-(

Jack Krooss  9:22 AM
Intermittents are the worst!
9:22
So, got it in the error state and Returned and this time no error message.
9:23
Also, I am in the country and on a very funky microwave internet...

Jack Krooss  9:35 AM
So, closed and restarted Tulip dev env and it still can get into the error state after navigating around and going back into player.
9:35
Will try rebooting PC
9:36
Actually first logging out of Tulip
9:38
I will stop play by play...have a good day... will summarize results in github

**Comment by jackkrooss** [comment]
Continuing:
Just logged out of Tulip and logged back in. Upon entry SM (shipping manager) is in "customer name error state" (CNES).
![image](https://user-images.githubusercontent.com/64096573/87857436-75ebc480-c8db-11ea-9b19-a7218ee81350.png)
Return and Ship and SM is in "customer name correct state" (CNCS).
![image](https://user-images.githubusercontent.com/64096573/87857462-b21f2500-c8db-11ea-8822-32dced93319d.png)

**Comment by jackkrooss** [comment]
Note above that the DESTINATION field in the table is also in error/correct state

**Comment by jackkrooss** [comment]
Went back to Tulip Player after typing the above comment and we are back to CNES (error state):
![image](https://user-images.githubusercontent.com/64096573/87857518-41c4d380-c8dc-11ea-8dcc-3688db0b8dd0.png)

**Comment by jackkrooss** [comment]
Will now try to close all windows and  reboot PC and see what happens. My bet is same performance.

**Comment by jackkrooss** [comment]
So, reboot and start Tulip Player and we are in CNES (error state):
![image](https://user-images.githubusercontent.com/64096573/87857670-4dfd6080-c8dd-11ea-8b87-d18cc2444bbb.png)
Return and Ship and ENCS (correct state):
![image](https://user-images.githubusercontent.com/64096573/87857691-8866fd80-c8dd-11ea-8a53-5c400c0bb3a1.png)

**Comment by jackkrooss** [comment]
I think at this point we should see if this behavior is repeatable by someone else.

**Comment by jackkrooss** [comment]
Just saw something different. Left Tulip Player to do some other things, reentered the window and the customer name was still in the selected order pane, but the table had changed and no longer included the the customer name.
![image](https://user-images.githubusercontent.com/64096573/87863236-e4e21100-c90d-11ea-8fe8-9f90d25942fe.png)

**Comment by jackkrooss** [comment]
So, my theory is that the connector function you modified runs when the page is entered, but there is some other time that a function runs (perhaps a periodic automatic refresh) that uses the old function.

**Comment by jackkrooss** [comment]
More... I can get the error state by just using the paging arrows! 

Enter screen:
![image](https://user-images.githubusercontent.com/64096573/87863278-5f129580-c90e-11ea-84f2-c71d6a364fe6.png)

Page forward/page back:
![image](https://user-images.githubusercontent.com/64096573/87863297-7a7da080-c90e-11ea-8774-02fb4b7ad77e.png)

**Comment by ilya-bass** [comment]
@jackkrooss  I fixed the paging arrows in SN and No-SN screens. I think that's all of it, please test and see if you can also repro the "leave the window" case because I still don't understand the connection there...

**Comment by ilya-bass** [comment]
OOOOHH my Lord.  I found it.  There is a timer trigger that does automatic refresh!!

**Comment by ilya-bass** [comment]
ok, fixed everywhere now.  With real code, I would have been able to avoid this :-(

**Comment by jackkrooss** [comment]
Thought so
