### ISSUE TITLE
Executive summary view

### ISSUE THREAD

**Issue by sanj-maskson** [tulip/ppe-logistics#26]
I need a high level overview of how we're doing that I can quickly share out daily:

Critical:
- how many masks have we shipped
- how many hospitals/sites have we shipped to

Less critical:
- Exactly which hospitals we're in
- total masks in backlog of requests
- total of hospitals in backlog

Ideally this is broken down by date, and has a summary column

**Comment by markfreedmantulip** [comment]
@sanj-maskson please review and close out this request if you are happy with the result
https://datastudio.google.com/s/uLJxedgn84Y

**Comment by sanj-maskson** [comment]
It'd be helpful to clear out orders sent to home.  Perhaps a filter for >=5 masks would help.

And can we add up orders of different sizes?  I really want "100 to Beverly, 50 to Queens"

**Comment by markfreedmantulip** [comment]
@sanj-maskson is this completed?
