### ISSUE TITLE
Add Contact email to orders dashboard

### ISSUE THREAD

**Issue by bsauln** [tulip/ppe-logistics#28]
https://datastudio.google.com/u/0/reporting/1lfL3n_MSg-T33BIw0qj3BkLeAI8Q_RUp/page/MAAKB?s=o6u9KXA3XeE

Please add a column that includes the contact email when sorting through the orders dashboard.

**Comment by markfreedmantulip** [comment]
@bsauln updated - please confirm and close this request

**Comment by bsauln** [comment]
Looks good!
