### ISSUE TITLE
"Orders" screen for CSRs

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#38]
1. We cannot see the order statuses well on the left side of this screen.
2. Would be nice to be able to see tracking numbers for orders that have shipped.
3. When we click the 'Update notes' button on the Order notes, Hold, CSR Review, Open buttons - the right data fields go blank and we have to re-lookup the customer, order, institution to ensure the updates were committed to the records.  This could use some streamlining like the 'Create Order' screen.

**Comment by markfreedmantulip** [comment]
1. order status has been rearranged.
2. dashboard can be used for tracking numbers for the time being
3. splitting off this request

**Comment by AmyLee1920** [comment]
1 and 2 rearrangement works thanks. Noted 3 comment above on the split-off request.
