### ISSUE TITLE
New Order - seeing old order lines

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#39]
When I tried to open a new order this morning, I saw old closed/shipped order lines in the shopping cart. When I clear the cart, the screen went blank and needed to re-lookup/enter the institution/client information again.

**Comment by markfreedmantulip** [comment]
Fixed on future orders, please review

**Comment by markfreedmantulip** [comment]
all active carts have been cleared

**Comment by AmyLee1920** [comment]
I think this is fixed now.
