### ISSUE TITLE
New Orders - going to status open

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#40]
New orders this am were going to a status of 'Open' rather than 'Review' this would mean that new orders entered in the system are automatically visible by Lightspeed before CSRs have a chance to vet the client/order and could be shipped before ready. Seeing too many problems this am with Order entry - asked CSR's to cease any order entry until problems are addressed.

**Comment by markfreedmantulip** [comment]
Fixed. please review

**Comment by AmyLee1920** [comment]
Fixed.
