### ISSUE TITLE
New Order - Cannot submit cart.

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#42]
MO208 was entered this am for adapters only just fine. MO209 - same process in Tulip, click the 'Submit Cart' button, yellow confirmation that order was created pops up. Switch over to Orders screen and cannot find MO209. Back to Create Order screen - search for same institution/client and see MO209 still in cart...click 'Submit Cart' again, but order again not visible from Orders screen. Seems like something is wrong with the 'Submit Cart' process.

**Comment by markfreedmantulip** [comment]
MO209 should be in review status. Please back into the navigation screen and then into CSR - place order to test the changes

**Comment by AmyLee1920** [comment]
I think this is fixed.
