### ISSUE TITLE
Fulfillment Dashboard - showing additional records today that were not there yesterday

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#43]
Yesterday Brad and I ran a report to find all of the V2 S/M and L/XL in closed status in order to advise clients that they would be receiving new injection molded adapters. The report returned 50 records yesterday. Today the report returns 70 records and some of the individual orders on today's report include individuals who should have been advised in messaging yesterday that they would receive new adapters. Examples include: MO131, MO175, MO160, MO108 - these individual records were not present for example yesterday and are today on same report, same report filter status. Did a table-join type change for this report perhaps overnight? Concerned we may be missing other records that need to be advised for recall/replacement purposes using this report.

**Comment by markfreedmantulip** [comment]
I do not know what query you were running - from what I can tell MO160 was delivered on 4/5, for example.

**Comment by AmyLee1920** [comment]
MasksOn Fulfillment Dashboard Page 5 of 8 - Orders and Inventory. We filtered for Status=CLOSED and Product = PPE L/XL v2 or PPE S/M v2. Yesterday there were 50 records presented, today there were 70. Some of that difference was because of orders opened between yesterday and today; however the examples I noted above were not on the report yesterday, but were on the report today with same filtering.

**Comment by markfreedmantulip** [comment]
unable to reproduce this error
