### ISSUE TITLE
double load of institution dropdown on 'create order' screen

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#46]
I think there may be a double-load happening in the institution list dropdown on the 'Create Order' screen. When CSR navigates from one of the other screens to 'Create Order' screen, and selects the dropdown, the list appears, fades out, then reappears like it is reloading.

**Comment by markfreedmantulip** [comment]
whenever users click on any of the buttons on the bottom i am having the app reload entirely - this forces users to automatically be pushed to the newest version (because i imagine they will stay in this screen all the time and I don't want them on previous versions)

**Comment by AmyLee1920** [comment]
There is no additional click happening after the initial click of the dropdown menu. Click dropdown menu, wait a second, menu fades quick and reappears like it's refreshing more than the initial click of the dropdown. 

The app reload is creating a lot of additional clicks and reloads on this page. Particularly because CSR's are creating so many new institution/clients vs. picking from existing. When create new institution/client, on every order, the CSR then has to re-lookup that same institution/client in order to apply an order to their cart. If they don't do it this way, it results in abandoned carts. Right after entering institution/client, and re-looking them up to apply the order - CSR's almost always are switching to the "Customers" or "Orders" screens. "Customers" screen in order to approve the customer or update anything they need to from the initial create institution/client button push on the 'Create Order' screen because sometimes that information doesn't come with the customer, or the CSR sees it on the form after they already created the institution/client. Then they are going to the "Orders" screen to note order notes etc. because there is not a place to do that on the "Create Order" screen, and to open the order. After this they are likely searching again for the Order on the "Orders" screen to be assured that the system stored everything the way they intended the order to go in. There is a lot of re-looking-up and double-checking system is committing updates in current CSR workflow.
