### ISSUE TITLE
QTY  field on P5 of MO Fulfillment Dashboard - Orders & Inventory

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#54]
I think the QTY field is intended to be a total quantity of masks on an order, but it is not calculating correctly after spot-checking a few orders. Ex: MO199 has 4 masks on order but QTY=2 MO167 has 2 masks on order, but QTY=1

**Comment by markfreedmantulip** [comment]
this is intentional - MO199 has two lines on the order, the qty is representative of the order line quantity
![image](https://user-images.githubusercontent.com/63469492/79574742-9fa01000-808e-11ea-8897-bd8990e58a0a.png)
