### ISSUE TITLE
New issue with Create Order over to Orders screen today

### ISSUE THREAD

**Issue by AmyLee1920** [tulip/ppe-logistics#58]
Advise to CSRs: On the Orders Screen - I'm seeing a new issue today where the Delivery address is not auto-filling with what we indicate on the Create Order screen - the addresses entered on Create Order  screen will be in the dropdown on the Orders screen - so make sure you pick the right one and click the 'Change Address' button on the Orders screen before you 'Open' the order.

**Comment by markfreedmantulip** [comment]
phone call with amy to view - changes made 
1. google will now update the address you typed in and show the returned address (still need to implement validation)
2. new client is being set to primary upon creation
3. approve user should no longer blank the screen
4. delivery address... surprised to see that not pop up correctly when clicking on the order in orders screen. please verify this is still occurring
