### ISSUE TITLE
Even simpler exec dashboard

### ISSUE THREAD

**Issue by sanj-maskson** [tulip/ppe-logistics#60]
see here for a mockup

https://docs.google.com/spreadsheets/d/1bgD_Zadbn2yzanY5V8eL954jd-6L1TRb3XymtH2nvZw/edit

**Comment by ilya-bass** [comment]
@sanj-maskson I added the last page (9) to the [report](https://datastudio.google.com/u/0/reporting/1lfL3n_MSg-T33BIw0qj3BkLeAI8Q_RUp/page/ojYOB), see if it meets your needs?  It's not exactly the same as in your template, but the data studio has its limitations...

**Comment by ilya-bass** [comment]
I think we are good for now after fixing one of the metrics yesterday
