### ISSUE TITLE
generic dashboard

### ISSUE THREAD

**Issue by markfreedmantulip** [tulip/ppe-logistics#73]
a generic dashboard for all suppliers (our use) - duplicate and modify filter when new suppliers come online

**Comment by ilya-bass** [comment]
Tracking progress here https://docs.google.com/spreadsheets/d/1QR-x-nM868vzzuKq8pVaBIgWljCGwpwear8eTrBFVzA/edit#gid=0

**Comment by ilya-bass** [comment]
I think this can be closed as done with the current state of things.  Great work @ianslai
