### ISSUE TITLE
monday.com integration

### ISSUE THREAD

**Issue by markfreedmantulip** [tulip/ppe-logistics#75]

**Comment by ilya-bass** [comment]
@markfreedmantulip I added "additional notes" to my [app example](https://trial-looking-to-help-ppelogisticsorg-ef.tulip.co/groups/FSF62Cvsd8DHCnRaC/processes/HkFio79hpao59Fqnk/versions/M4YDuCywB9Xbfw3da/steps/CxKToPWnwrrKQtMcn).  It's yet another substitution in the template, so you will need to update the template and also add `__additional_notes__ `substitution in the list of trigger actions.  Note that I also renamed the substitution result variable to MondayColumnsFinal for clarity, hope that does not screw up your process of adopting this to your example.  Shout if anything is unclear or other help needed.
